### ISSUE TITLE
Buscar probemas del metodo "invertirPalabra"

### ISSUE THREAD

**Issue by daaniimr** [nakayoshi-dango/Grupo-Testing-D-GestorPalabras#2]
Subir el testInvertirPalabra.java

**Comment by David0Gs** [comment]
Teniamos el siguiente metodo:
public static String invertirPalabra(String palabra) {
        StringBuilder resultado = new StringBuilder();
        for (int i = palabra.length() - 2; i >= 0; i--) {
            resultado.append(palabra.charAt(i));
        }
        return resultado.toString();
    }
Para arreglarlo, hemos cambiado el valor de int i dentro del bucle for por int i = palabra.length() - 1
